export {default as Login} from './Login/Login'
export {default as Shop} from './Shop/Shop'
export {default as ProductDetail} from './ProductDetail/ProductDetail'
export {default as Cart} from './Cart/Cart'
export {default as Orders} from './Orders/Orders'
export {default as Signup} from './Signup/Signup'
export {default as Home} from './Home/Home'